# Generated by Django 4.2.1 on 2023-06-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegister',
            fields=[
                ('tournamentId', models.IntegerField(primary_key=True, serialize=False)),
                ('registerUserId', models.IntegerField()),
                ('tournamentName', models.TextField()),
                ('tournamentLevel', models.TextField()),
                ('hostSchool', models.TextField()),
                ('managerName', models.TextField()),
                ('managerEmail', models.TextField()),
                ('managerPhone', models.TextField()),
                ('tournamentCity', models.TextField()),
                ('tournamentState', models.TextField()),
            ],
            options={
                'db_table': 'speech_tournaments',
                'managed': True,
            },
        ),
    ]
