# Generated by Django 4.2.1 on 2023-06-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSignup',
            fields=[
                ('competitorId', models.IntegerField(primary_key=True, serialize=False)),
                ('schoolKey', models.CharField(max_length=1)),
                ('tournamentId', models.IntegerField()),
                ('registerUserId', models.IntegerField()),
                ('competitorSchool', models.TextField()),
                ('coachName', models.TextField()),
                ('coachEmail', models.TextField()),
                ('coachPhone', models.TextField()),
            ],
            options={
                'db_table': 'speech_competitors',
                'managed': True,
            },
        ),
    ]
